backend:
  name: turbo-github
  turbo_site_id: 81991617-86d5-4b92-b2bc-9814807ee2d6
  branch: main

media_folder: images
public_folder: /images

site_url: https://canadafei.github.io

collections:
  - name: posts
    label: Posts
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - name: title
        label: Title
        widget: string

      - name: date
        label: Date
        widget: datetime

      - name: body
        label: Body
        widget: markdown

  - name: albums
    label: Albums
    folder: _albums
    create: true

    fields:
      - name: title
        label: Title
        widget: string

      - name: date
        label: Date
        widget: datetime

      - name: images
        label: Photos
        widget: list

        fields:
          - name: image
            label: Image
            widget: image
