backend:
  name: turbo-github
  turbo_site_id: 81991617-86d5-4b92-b2bc-9814807ee2d6
  branch: main



media_folder: "images"
public_folder: "/images"

site_url: https://canadafei.github.io

collections:
  - name: "posts"
    label: "文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "日期"
        name: "date"
        widget: "datetime"

      - label: "正文"
        name: "body"
        widget: "markdown"

         - name: "albums"

         
    label: "图片集"
    folder: "_albums"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "发布时间"
        name: "date"
        widget: "datetime"

      - label: "图片"
        name: "images"
        widget: "list"
        field:
          label: "图片"
          name: "image"
          widget: "image"
